events {
  worker_connections  4096;  ## Default: 1024
}

stream {

    server {
        listen     30000;
        #TCP traffic will be forwarded to the "stream_backend" upstream group
        proxy_pass kafka-0.kafka-svc.kafka.svc.cluster.local:9092;
    }

    server {
        listen     30001;
        #TCP traffic will be forwarded to the "stream_backend" upstream group
        proxy_pass kafka-1.kafka-svc.kafka.svc.cluster.local:9092;
    }

    # server {
    #     listen     30002;
    #     #TCP traffic will be forwarded to the "stream_backend" upstream group
    #     proxy_pass kafka-2.kafka-svc.kafka.svc.cluster.local:9092;
    # }

    # server {
    #     listen     30003;
    #     #TCP traffic will be forwarded to the "stream_backend" upstream group
    #     proxy_pass kafka-3.kafka-svc.kafka.svc.cluster.local:9092;
    # }

    # server {
    #     listen     30004;
    #     #TCP traffic will be forwarded to the "stream_backend" upstream group
    #     proxy_pass kafka-4.kafka-svc.kafka.svc.cluster.local:9092;
    # }
}