
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ctl-cfg
  namespace: kafka
data:
  CTL_REPLICAS: "1"
  CTL_HOSTNAME_PREFIX: "kafka-kraft"
  CLUSTER_ID: "FroGkXidSBuRYv_ndR36-Q"
  KAFKA_BROKER_ID: "-1"
  SERVICE: "kafka-svc"
  SHARE_DIR: "/mnt/kafka"
  NAMESPACE: "kafka-ns"
  SERVICE_FQDN: "kafka-svc.kafka.svc.cluster.local"
  FMT_DIR: "Y"
  TIMEOUT: '600'
  EXTERNAL_IP: "192.168.58.2"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-kraft
  labels:
    app: kafka-app
  namespace: kafka
spec:
  serviceName: kafka-svc
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-kraft-container
          image: my_kraft:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: kafka-ctl-cfg
          env:
            - name: REPLICAS
              value: '1'
            - name: DEFAULT_REPLICATION_FACTOR
              value: '3'
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: '2'
            - name: IS_CONTROLLER
              value: 'YES'
            - name: CFG_FILE
              value: 'config/kraft/controller.properties'
          volumeMounts:
            - name: data
              mountPath: /mnt/kafka

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka-app
  namespace: kafka
spec:
  serviceName: kafka-svc
  replicas: 2
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-container
          image: my_kraft:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: kafka-ctl-cfg
          env:
            - name: REPLICAS
              value: '1'
            - name: DEFAULT_REPLICATION_FACTOR
              value: '3'
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: '2'
            - name: IS_CONTROLLER
              value: 'NO'
            - name: CFG_FILE
              value: 'config/kraft/broker.properties'
          volumeMounts:
            - name: data
              mountPath: /mnt/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
